//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 04:39:37 PM CEST 
//


package org.inanme.spring.ws.types;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "getCourseRequest")
public class GetCourseRequest {

    @XmlAttribute(name = "courseId", required = true)
    protected String courseId;

    /**
     * Gets the value of the courseId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * Sets the value of the courseId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCourseId(String value) {
        this.courseId = value;
    }
}
